-- Network Agenda - Supabase/Postgres starter schema
-- Run this in the Supabase SQL Editor before migrating the FastAPI backend.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  birth_date text not null default '',
  email text not null unique,
  password_hash text not null default '',
  phone text not null,
  phone_digits text not null unique,
  cep text not null default '',
  address text not null default '',
  address_line text not null default '',
  address_number text not null default '',
  address_complement text not null default '',
  neighborhood text not null default '',
  city text not null default '',
  state text not null default '',
  address_visible boolean not null default false,
  interests text not null default '[]',
  is_collaborator boolean not null default false,
  offered_services text not null default '',
  use_different_service_address boolean not null default false,
  service_cep text not null default '',
  service_address text not null default '',
  service_address_line text not null default '',
  service_address_number text not null default '',
  service_address_complement text not null default '',
  service_neighborhood text not null default '',
  service_city text not null default '',
  service_state text not null default '',
  service_address_visible boolean not null default true,
  public_visible boolean not null default false,
  public_description text not null default '',
  public_demand text not null default '',
  public_solves text not null default '',
  public_tags text not null default '',
  public_whatsapp text not null default '',
  public_instagram text not null default '',
  public_linkedin text not null default '',
  public_url text not null default '',
  google_connected boolean not null default false,
  google_contacts_imported_at text not null default '',
  google_profile_synced_at text not null default '',
  notification_preference text not null default 'relevant',
  role text not null default 'user',
  created_at timestamptz not null default now()
);

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  owner_id text not null default 'demo-user',
  name text not null,
  phone text not null,
  service text not null,
  note text not null default '',
  city text not null default '',
  address text not null default '',
  trust text not null default 'Novo',
  source text not null default 'Manual',
  description text not null default '',
  demand text not null default '',
  solves text not null default '',
  tags text not null default '',
  email text not null default '',
  whatsapp text not null default '',
  instagram text not null default '',
  linkedin text not null default '',
  custom_url text not null default '',
  custom_fields text not null default '[]',
  crm_status text not null default 'Novo',
  crm_priority text not null default 'Média',
  last_contact_at text not null default '',
  next_follow_up_at text not null default '',
  crm_note text not null default '',
  category_id text not null,
  category_label text not null,
  category_group text not null,
  search_text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.public_profiles (
  id bigint generated by default as identity primary key,
  name text not null,
  service text not null,
  area text not null,
  people integer not null,
  response text not null,
  score numeric not null,
  category_id text not null,
  category_label text not null,
  category_group text not null,
  search_text text not null
);

create table if not exists public.merge_suggestions (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  primary_contact_id bigint not null,
  duplicate_contact_id bigint not null,
  match_type text not null,
  match_value text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  unique(owner_id, primary_contact_id, duplicate_contact_id, match_type, match_value)
);

create table if not exists public.contact_phones (
  id bigint generated by default as identity primary key,
  contact_id bigint not null,
  owner_id text not null,
  phone text not null,
  phone_digits text not null,
  ddd text not null default '',
  label text not null default 'Principal',
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  unique(contact_id, phone_digits)
);

create table if not exists public.contact_emails (
  id bigint generated by default as identity primary key,
  contact_id bigint not null,
  owner_id text not null,
  email text not null,
  normalized_email text not null,
  label text not null default 'Principal',
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  unique(contact_id, normalized_email)
);

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  name text not null,
  normalized_name text not null,
  usage_count integer not null default 0,
  created_at timestamptz not null default now(),
  unique(owner_id, normalized_name)
);

create table if not exists public.contact_tags (
  contact_id bigint not null,
  tag_id bigint not null,
  owner_id text not null,
  created_at timestamptz not null default now(),
  unique(contact_id, tag_id)
);

create table if not exists public.custom_fields (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  scope_type text not null default 'user',
  scope_id text not null default '',
  name text not null,
  field_key text not null,
  field_type text not null default 'text_short',
  options text not null default '[]',
  created_at timestamptz not null default now(),
  unique(owner_id, scope_type, scope_id, field_key)
);

create table if not exists public.custom_field_values (
  contact_id bigint not null,
  field_id bigint not null,
  owner_id text not null,
  value text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(contact_id, field_id)
);

create table if not exists public.groups (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  name text not null,
  area text not null default '',
  people_goal integer not null default 3,
  description text not null default '',
  created_by_email text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.group_members (
  id bigint generated by default as identity primary key,
  group_id bigint not null,
  user_id text not null default '',
  email text not null default '',
  role text not null default 'member',
  status text not null default 'active',
  created_at timestamptz not null default now(),
  unique(group_id, email)
);

create table if not exists public.group_contacts (
  group_id bigint not null,
  contact_id bigint not null,
  owner_id text not null,
  added_by text not null default '',
  created_at timestamptz not null default now(),
  unique(group_id, contact_id)
);

create table if not exists public.group_messages (
  id bigint generated by default as identity primary key,
  group_id bigint not null,
  sender_id text not null,
  sender_name text not null default '',
  sender_email text not null default '',
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.users add column if not exists notification_preference text not null default 'relevant';

create index if not exists contacts_owner_created_idx on public.contacts(owner_id, created_at desc, id desc);
create index if not exists contacts_owner_category_idx on public.contacts(owner_id, category_id);
create index if not exists contacts_owner_follow_up_idx on public.contacts(owner_id, next_follow_up_at);
create index if not exists contacts_search_text_idx on public.contacts using gin(to_tsvector('simple', search_text));
create index if not exists public_profiles_search_text_idx on public.public_profiles using gin(to_tsvector('simple', search_text));
create index if not exists users_public_visible_idx on public.users(public_visible, created_at desc);
create index if not exists contact_phones_owner_ddd_idx on public.contact_phones(owner_id, ddd);
create index if not exists contact_phones_digits_idx on public.contact_phones(owner_id, phone_digits);
create index if not exists contact_emails_normalized_idx on public.contact_emails(owner_id, normalized_email);
create index if not exists tags_owner_name_idx on public.tags(owner_id, normalized_name);
create index if not exists contact_tags_owner_idx on public.contact_tags(owner_id, tag_id);
create index if not exists custom_field_values_owner_idx on public.custom_field_values(owner_id, field_id);
create index if not exists groups_owner_idx on public.groups(owner_id, created_at desc);
create index if not exists group_members_group_idx on public.group_members(group_id, status);
create index if not exists group_members_user_idx on public.group_members(user_id, email);
create index if not exists group_contacts_group_idx on public.group_contacts(group_id, created_at desc);
create index if not exists group_contacts_contact_idx on public.group_contacts(contact_id);
create index if not exists group_messages_group_idx on public.group_messages(group_id, created_at asc);

-- Do not expose these tables directly to the browser until RLS policies are finalized.
-- The current FastAPI app enforces owner isolation in application code.
-- The policies below provide a baseline if tables are later accessed from Supabase clients.

create or replace function public.current_app_user_id()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select id::text
  from public.users
  where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  limit 1;
$$;

create or replace function public.current_app_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.users
    where id::text = public.current_app_user_id()
      and role = 'admin'
  );
$$;

create or replace function public.can_access_group(p_group_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_app_is_admin()
    or exists (
      select 1
      from public.groups
      where id = p_group_id
        and owner_id = public.current_app_user_id()
    )
    or exists (
      select 1
      from public.group_members
      where group_id = p_group_id
        and status = 'active'
        and (
          user_id = public.current_app_user_id()
          or lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
        )
    );
$$;

create or replace function public.can_manage_group(p_group_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_app_is_admin()
    or exists (
      select 1
      from public.groups
      where id = p_group_id
        and owner_id = public.current_app_user_id()
    )
    or exists (
      select 1
      from public.group_members
      where group_id = p_group_id
        and status = 'active'
        and role in ('owner', 'admin')
        and (
          user_id = public.current_app_user_id()
          or lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
        )
    );
$$;

alter table public.users enable row level security;
alter table public.contacts enable row level security;
alter table public.public_profiles enable row level security;
alter table public.merge_suggestions enable row level security;
alter table public.contact_phones enable row level security;
alter table public.contact_emails enable row level security;
alter table public.tags enable row level security;
alter table public.contact_tags enable row level security;
alter table public.custom_fields enable row level security;
alter table public.custom_field_values enable row level security;
alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.group_contacts enable row level security;
alter table public.group_messages enable row level security;

drop policy if exists users_select_own_or_admin on public.users;
create policy users_select_own_or_admin on public.users
  for select to authenticated
  using (id::text = public.current_app_user_id() or public.current_app_is_admin());

drop policy if exists users_insert_own_email on public.users;
create policy users_insert_own_email on public.users
  for insert to authenticated
  with check (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));

drop policy if exists users_update_own_or_admin on public.users;
create policy users_update_own_or_admin on public.users
  for update to authenticated
  using (id::text = public.current_app_user_id() or public.current_app_is_admin())
  with check (id::text = public.current_app_user_id() or public.current_app_is_admin());

drop policy if exists contacts_owner_all on public.contacts;
create policy contacts_owner_all on public.contacts
  for all to authenticated
  using (owner_id = public.current_app_user_id() or public.current_app_is_admin())
  with check (owner_id = public.current_app_user_id() or public.current_app_is_admin());

drop policy if exists public_profiles_read_authenticated on public.public_profiles;
create policy public_profiles_read_authenticated on public.public_profiles
  for select to authenticated
  using (true);

drop policy if exists merge_suggestions_owner_all on public.merge_suggestions;
create policy merge_suggestions_owner_all on public.merge_suggestions
  for all to authenticated
  using (owner_id = public.current_app_user_id() or public.current_app_is_admin())
  with check (owner_id = public.current_app_user_id() or public.current_app_is_admin());

drop policy if exists contact_phones_owner_all on public.contact_phones;
create policy contact_phones_owner_all on public.contact_phones
  for all to authenticated
  using (owner_id = public.current_app_user_id() or public.current_app_is_admin())
  with check (owner_id = public.current_app_user_id() or public.current_app_is_admin());

drop policy if exists contact_emails_owner_all on public.contact_emails;
create policy contact_emails_owner_all on public.contact_emails
  for all to authenticated
  using (owner_id = public.current_app_user_id() or public.current_app_is_admin())
  with check (owner_id = public.current_app_user_id() or public.current_app_is_admin());

drop policy if exists tags_owner_all on public.tags;
create policy tags_owner_all on public.tags
  for all to authenticated
  using (owner_id = public.current_app_user_id() or public.current_app_is_admin())
  with check (owner_id = public.current_app_user_id() or public.current_app_is_admin());

drop policy if exists contact_tags_owner_all on public.contact_tags;
create policy contact_tags_owner_all on public.contact_tags
  for all to authenticated
  using (owner_id = public.current_app_user_id() or public.current_app_is_admin())
  with check (owner_id = public.current_app_user_id() or public.current_app_is_admin());

drop policy if exists custom_fields_select_scope on public.custom_fields;
create policy custom_fields_select_scope on public.custom_fields
  for select to authenticated
  using (
    owner_id = public.current_app_user_id()
    or public.current_app_is_admin()
    or (scope_type = 'group' and scope_id ~ '^[0-9]+$' and public.can_access_group(scope_id::bigint))
  );

drop policy if exists custom_fields_write_scope on public.custom_fields;
create policy custom_fields_write_scope on public.custom_fields
  for all to authenticated
  using (
    owner_id = public.current_app_user_id()
    or public.current_app_is_admin()
    or (scope_type = 'group' and scope_id ~ '^[0-9]+$' and public.can_manage_group(scope_id::bigint))
  )
  with check (
    owner_id = public.current_app_user_id()
    or public.current_app_is_admin()
    or (scope_type = 'group' and scope_id ~ '^[0-9]+$' and public.can_manage_group(scope_id::bigint))
  );

drop policy if exists custom_field_values_select_scope on public.custom_field_values;
create policy custom_field_values_select_scope on public.custom_field_values
  for select to authenticated
  using (
    owner_id = public.current_app_user_id()
    or public.current_app_is_admin()
    or exists (
      select 1
      from public.custom_fields
      where custom_fields.id = custom_field_values.field_id
        and custom_fields.scope_type = 'group'
        and custom_fields.scope_id ~ '^[0-9]+$'
        and public.can_access_group(custom_fields.scope_id::bigint)
    )
  );

drop policy if exists custom_field_values_write_scope on public.custom_field_values;
create policy custom_field_values_write_scope on public.custom_field_values
  for all to authenticated
  using (
    owner_id = public.current_app_user_id()
    or public.current_app_is_admin()
    or exists (
      select 1
      from public.custom_fields
      where custom_fields.id = custom_field_values.field_id
        and custom_fields.scope_type = 'group'
        and custom_fields.scope_id ~ '^[0-9]+$'
        and public.can_manage_group(custom_fields.scope_id::bigint)
    )
  )
  with check (
    owner_id = public.current_app_user_id()
    or public.current_app_is_admin()
    or exists (
      select 1
      from public.custom_fields
      where custom_fields.id = custom_field_values.field_id
        and custom_fields.scope_type = 'group'
        and custom_fields.scope_id ~ '^[0-9]+$'
        and public.can_manage_group(custom_fields.scope_id::bigint)
    )
  );

drop policy if exists groups_select_member_or_admin on public.groups;
create policy groups_select_member_or_admin on public.groups
  for select to authenticated
  using (public.can_access_group(id));

drop policy if exists groups_insert_admin_only on public.groups;
create policy groups_insert_admin_only on public.groups
  for insert to authenticated
  with check (owner_id = public.current_app_user_id() and public.current_app_is_admin());

drop policy if exists groups_update_manager on public.groups;
create policy groups_update_manager on public.groups
  for update to authenticated
  using (public.can_manage_group(id))
  with check (public.can_manage_group(id));

drop policy if exists group_members_select_group_access on public.group_members;
create policy group_members_select_group_access on public.group_members
  for select to authenticated
  using (public.can_access_group(group_id));

drop policy if exists group_members_write_group_manager on public.group_members;
create policy group_members_write_group_manager on public.group_members
  for all to authenticated
  using (public.can_manage_group(group_id))
  with check (public.can_manage_group(group_id));

drop policy if exists group_contacts_select_group_access on public.group_contacts;
create policy group_contacts_select_group_access on public.group_contacts
  for select to authenticated
  using (public.can_access_group(group_id));

drop policy if exists group_contacts_write_group_manager on public.group_contacts;
create policy group_contacts_write_group_manager on public.group_contacts
  for all to authenticated
  using (public.can_manage_group(group_id))
  with check (public.can_manage_group(group_id));

drop policy if exists group_messages_select_group_access on public.group_messages;
create policy group_messages_select_group_access on public.group_messages
  for select to authenticated
  using (public.can_access_group(group_id));

drop policy if exists group_messages_insert_group_access on public.group_messages;
create policy group_messages_insert_group_access on public.group_messages
  for insert to authenticated
  with check (public.can_access_group(group_id) and sender_id = public.current_app_user_id());
