-- Network Agenda - Supabase/Postgres starter schema
-- Run this in the Supabase SQL Editor before migrating the FastAPI backend.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  birth_date text not null default '',
  email text not null unique,
  password_hash text not null default '',
  phone text not null,
  phone_digits text not null unique,
  cep text not null default '',
  address text not null default '',
  address_line text not null default '',
  address_number text not null default '',
  address_complement text not null default '',
  neighborhood text not null default '',
  city text not null default '',
  state text not null default '',
  address_visible boolean not null default false,
  interests text not null default '[]',
  is_collaborator boolean not null default false,
  offered_services text not null default '',
  use_different_service_address boolean not null default false,
  service_cep text not null default '',
  service_address text not null default '',
  service_address_line text not null default '',
  service_address_number text not null default '',
  service_address_complement text not null default '',
  service_neighborhood text not null default '',
  service_city text not null default '',
  service_state text not null default '',
  service_address_visible boolean not null default true,
  public_visible boolean not null default false,
  public_description text not null default '',
  public_demand text not null default '',
  public_solves text not null default '',
  public_tags text not null default '',
  public_whatsapp text not null default '',
  public_instagram text not null default '',
  public_linkedin text not null default '',
  public_url text not null default '',
  google_connected boolean not null default false,
  google_contacts_imported_at text not null default '',
  google_profile_synced_at text not null default '',
  role text not null default 'user',
  created_at timestamptz not null default now()
);

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  owner_id text not null default 'demo-user',
  name text not null,
  phone text not null,
  service text not null,
  note text not null default '',
  city text not null default '',
  address text not null default '',
  trust text not null default 'Novo',
  source text not null default 'Manual',
  description text not null default '',
  demand text not null default '',
  solves text not null default '',
  tags text not null default '',
  email text not null default '',
  whatsapp text not null default '',
  instagram text not null default '',
  linkedin text not null default '',
  custom_url text not null default '',
  custom_fields text not null default '[]',
  crm_status text not null default 'Novo',
  crm_priority text not null default 'Média',
  last_contact_at text not null default '',
  next_follow_up_at text not null default '',
  crm_note text not null default '',
  category_id text not null,
  category_label text not null,
  category_group text not null,
  search_text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.public_profiles (
  id bigint generated by default as identity primary key,
  name text not null,
  service text not null,
  area text not null,
  people integer not null,
  response text not null,
  score numeric not null,
  category_id text not null,
  category_label text not null,
  category_group text not null,
  search_text text not null
);

create table if not exists public.merge_suggestions (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  primary_contact_id bigint not null,
  duplicate_contact_id bigint not null,
  match_type text not null,
  match_value text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  unique(owner_id, primary_contact_id, duplicate_contact_id, match_type, match_value)
);

create table if not exists public.contact_phones (
  id bigint generated by default as identity primary key,
  contact_id bigint not null,
  owner_id text not null,
  phone text not null,
  phone_digits text not null,
  ddd text not null default '',
  label text not null default 'Principal',
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  unique(contact_id, phone_digits)
);

create table if not exists public.contact_emails (
  id bigint generated by default as identity primary key,
  contact_id bigint not null,
  owner_id text not null,
  email text not null,
  normalized_email text not null,
  label text not null default 'Principal',
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  unique(contact_id, normalized_email)
);

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  name text not null,
  normalized_name text not null,
  usage_count integer not null default 0,
  created_at timestamptz not null default now(),
  unique(owner_id, normalized_name)
);

create table if not exists public.contact_tags (
  contact_id bigint not null,
  tag_id bigint not null,
  owner_id text not null,
  created_at timestamptz not null default now(),
  unique(contact_id, tag_id)
);

create table if not exists public.custom_fields (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  scope_type text not null default 'user',
  scope_id text not null default '',
  name text not null,
  field_key text not null,
  field_type text not null default 'text_short',
  options text not null default '[]',
  created_at timestamptz not null default now(),
  unique(owner_id, scope_type, scope_id, field_key)
);

create table if not exists public.custom_field_values (
  contact_id bigint not null,
  field_id bigint not null,
  owner_id text not null,
  value text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(contact_id, field_id)
);

create table if not exists public.groups (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  name text not null,
  description text not null default '',
  created_by_email text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.group_members (
  id bigint generated by default as identity primary key,
  group_id bigint not null,
  user_id text not null default '',
  email text not null default '',
  role text not null default 'member',
  status text not null default 'active',
  created_at timestamptz not null default now(),
  unique(group_id, email)
);

create table if not exists public.group_contacts (
  group_id bigint not null,
  contact_id bigint not null,
  owner_id text not null,
  added_by text not null default '',
  created_at timestamptz not null default now(),
  unique(group_id, contact_id)
);

create index if not exists contacts_owner_created_idx on public.contacts(owner_id, created_at desc, id desc);
create index if not exists contacts_owner_category_idx on public.contacts(owner_id, category_id);
create index if not exists contacts_owner_follow_up_idx on public.contacts(owner_id, next_follow_up_at);
create index if not exists contacts_search_text_idx on public.contacts using gin(to_tsvector('simple', search_text));
create index if not exists public_profiles_search_text_idx on public.public_profiles using gin(to_tsvector('simple', search_text));
create index if not exists users_public_visible_idx on public.users(public_visible, created_at desc);
create index if not exists contact_phones_owner_ddd_idx on public.contact_phones(owner_id, ddd);
create index if not exists contact_phones_digits_idx on public.contact_phones(owner_id, phone_digits);
create index if not exists contact_emails_normalized_idx on public.contact_emails(owner_id, normalized_email);
create index if not exists tags_owner_name_idx on public.tags(owner_id, normalized_name);
create index if not exists contact_tags_owner_idx on public.contact_tags(owner_id, tag_id);
create index if not exists custom_field_values_owner_idx on public.custom_field_values(owner_id, field_id);
create index if not exists groups_owner_idx on public.groups(owner_id, created_at desc);
create index if not exists group_members_group_idx on public.group_members(group_id, status);
create index if not exists group_members_user_idx on public.group_members(user_id, email);
create index if not exists group_contacts_group_idx on public.group_contacts(group_id, created_at desc);
create index if not exists group_contacts_contact_idx on public.group_contacts(contact_id);

-- Do not expose these tables directly to the browser until RLS policies are finalized.
-- The current FastAPI app enforces owner isolation in application code.
