-- Network Agenda - Supabase/Postgres starter schema
-- Run this in the Supabase SQL Editor before migrating the FastAPI backend.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  birth_date text not null default '',
  email text not null unique,
  password_hash text not null default '',
  phone text not null,
  phone_digits text not null unique,
  cep text not null default '',
  address text not null default '',
  address_line text not null default '',
  address_number text not null default '',
  address_complement text not null default '',
  neighborhood text not null default '',
  city text not null default '',
  state text not null default '',
  address_visible boolean not null default false,
  interests jsonb not null default '[]'::jsonb,
  is_collaborator boolean not null default false,
  offered_services text not null default '',
  use_different_service_address boolean not null default false,
  service_cep text not null default '',
  service_address text not null default '',
  service_address_line text not null default '',
  service_address_number text not null default '',
  service_address_complement text not null default '',
  service_neighborhood text not null default '',
  service_city text not null default '',
  service_state text not null default '',
  service_address_visible boolean not null default true,
  public_visible boolean not null default false,
  public_description text not null default '',
  public_demand text not null default '',
  public_solves text not null default '',
  public_tags text not null default '',
  public_whatsapp text not null default '',
  public_instagram text not null default '',
  public_linkedin text not null default '',
  public_url text not null default '',
  google_connected boolean not null default false,
  google_contacts_imported_at text not null default '',
  google_profile_synced_at text not null default '',
  role text not null default 'user',
  created_at timestamptz not null default now()
);

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  owner_id text not null default 'demo-user',
  name text not null,
  phone text not null,
  service text not null,
  note text not null default '',
  city text not null default '',
  address text not null default '',
  trust text not null default 'Novo',
  source text not null default 'Manual',
  description text not null default '',
  demand text not null default '',
  solves text not null default '',
  tags text not null default '',
  email text not null default '',
  whatsapp text not null default '',
  instagram text not null default '',
  linkedin text not null default '',
  custom_url text not null default '',
  custom_fields jsonb not null default '[]'::jsonb,
  crm_status text not null default 'Novo',
  crm_priority text not null default 'Media',
  last_contact_at text not null default '',
  next_follow_up_at text not null default '',
  crm_note text not null default '',
  category_id text not null,
  category_label text not null,
  category_group text not null,
  search_text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.public_profiles (
  id bigint generated by default as identity primary key,
  name text not null,
  service text not null,
  area text not null,
  people integer not null,
  response text not null,
  score numeric not null,
  category_id text not null,
  category_label text not null,
  category_group text not null,
  search_text text not null
);

create table if not exists public.merge_suggestions (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  primary_contact_id bigint not null,
  duplicate_contact_id bigint not null,
  match_type text not null,
  match_value text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  unique(owner_id, primary_contact_id, duplicate_contact_id, match_type, match_value)
);

create index if not exists contacts_owner_created_idx on public.contacts(owner_id, created_at desc, id desc);
create index if not exists contacts_owner_category_idx on public.contacts(owner_id, category_id);
create index if not exists contacts_owner_follow_up_idx on public.contacts(owner_id, next_follow_up_at);
create index if not exists contacts_search_text_idx on public.contacts using gin(to_tsvector('simple', search_text));
create index if not exists public_profiles_search_text_idx on public.public_profiles using gin(to_tsvector('simple', search_text));
create index if not exists users_public_visible_idx on public.users(public_visible, created_at desc);

-- Do not expose these tables directly to the browser until RLS policies are finalized.
-- The current FastAPI app enforces owner isolation in application code.
