create table if not exists users (
  id bigint generated by default as identity primary key,
  name text not null,
  birth_date text not null default '',
  email text not null unique,
  password_hash text not null default '',
  phone text not null,
  phone_digits text not null unique,
  cep text not null default '',
  address text not null default '',
  address_line text not null default '',
  address_number text not null default '',
  address_complement text not null default '',
  neighborhood text not null default '',
  city text not null default '',
  state text not null default '',
  address_visible boolean not null default false,
  interests text not null default '[]',
  is_collaborator boolean not null default false,
  offered_services text not null default '',
  use_different_service_address boolean not null default false,
  service_cep text not null default '',
  service_address text not null default '',
  service_address_line text not null default '',
  service_address_number text not null default '',
  service_address_complement text not null default '',
  service_neighborhood text not null default '',
  service_city text not null default '',
  service_state text not null default '',
  service_address_visible boolean not null default true,
  public_visible boolean not null default false,
  public_description text not null default '',
  public_demand text not null default '',
  public_solves text not null default '',
  public_tags text not null default '',
  public_whatsapp text not null default '',
  public_instagram text not null default '',
  public_linkedin text not null default '',
  public_url text not null default '',
  avatar_url text not null default '',
  google_connected boolean not null default false,
  google_contacts_imported_at text not null default '',
  google_profile_synced_at text not null default '',
  notification_preference text not null default 'relevant',
  role text not null default 'user',
  created_at timestamptz not null default now()
);

create table if not exists contacts (
  id bigint generated by default as identity primary key,
  owner_id text not null default 'demo-user',
  linked_user_id text not null default '',
  linked_user_name text not null default '',
  linked_user_email text not null default '',
  name text not null,
  phone text not null,
  service text not null,
  note text not null default '',
  city text not null default '',
  address text not null default '',
  trust text not null default 'Novo',
  source text not null default 'Manual',
  description text not null default '',
  demand text not null default '',
  demand_tags text not null default '',
  solves text not null default '',
  tags text not null default '',
  email text not null default '',
  whatsapp text not null default '',
  instagram text not null default '',
  linkedin text not null default '',
  organization text not null default '',
  custom_url text not null default '',
  avatar_url text not null default '',
  custom_fields text not null default '[]',
  crm_status text not null default 'Novo',
  crm_priority text not null default 'Média',
  last_contact_at text not null default '',
  next_follow_up_at text not null default '',
  crm_note text not null default '',
  category_id text not null,
  category_label text not null,
  category_group text not null,
  search_text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public_profiles (
  id bigint generated by default as identity primary key,
  name text not null,
  service text not null,
  area text not null,
  people integer not null,
  response text not null,
  score numeric not null,
  category_id text not null,
  category_label text not null,
  category_group text not null,
  search_text text not null
);

create table if not exists merge_suggestions (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  primary_contact_id bigint not null,
  duplicate_contact_id bigint not null,
  match_type text not null,
  match_value text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  unique(owner_id, primary_contact_id, duplicate_contact_id, match_type, match_value)
);

create table if not exists contact_phones (
  id bigint generated by default as identity primary key,
  contact_id bigint not null,
  owner_id text not null,
  phone text not null,
  phone_digits text not null,
  ddd text not null default '',
  label text not null default 'Principal',
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  unique(contact_id, phone_digits)
);

create table if not exists contact_emails (
  id bigint generated by default as identity primary key,
  contact_id bigint not null,
  owner_id text not null,
  email text not null,
  normalized_email text not null,
  label text not null default 'Principal',
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  unique(contact_id, normalized_email)
);

create table if not exists tags (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  name text not null,
  normalized_name text not null,
  usage_count integer not null default 0,
  created_at timestamptz not null default now(),
  unique(owner_id, normalized_name)
);

create table if not exists contact_tags (
  contact_id bigint not null,
  tag_id bigint not null,
  owner_id text not null,
  created_at timestamptz not null default now(),
  unique(contact_id, tag_id)
);

create table if not exists custom_fields (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  scope_type text not null default 'user',
  scope_id text not null default '',
  name text not null,
  field_key text not null,
  field_type text not null default 'text_short',
  options text not null default '[]',
  created_at timestamptz not null default now(),
  unique(owner_id, scope_type, scope_id, field_key)
);

create table if not exists custom_field_values (
  contact_id bigint not null,
  field_id bigint not null,
  owner_id text not null,
  value text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(contact_id, field_id)
);

create table if not exists groups (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  name text not null,
  area text not null default '',
  people_goal integer not null default 3,
  description text not null default '',
  created_by_email text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists group_members (
  id bigint generated by default as identity primary key,
  group_id bigint not null,
  user_id text not null default '',
  email text not null default '',
  role text not null default 'member',
  status text not null default 'active',
  created_at timestamptz not null default now(),
  unique(group_id, email)
);

create table if not exists group_contacts (
  group_id bigint not null,
  contact_id bigint not null,
  owner_id text not null,
  added_by text not null default '',
  created_at timestamptz not null default now(),
  unique(group_id, contact_id)
);

create table if not exists group_messages (
  id bigint generated by default as identity primary key,
  group_id bigint not null,
  sender_id text not null,
  sender_name text not null default '',
  sender_email text not null default '',
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists chat_threads (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  title text not null default '',
  last_message_preview text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists chat_messages (
  id bigint generated by default as identity primary key,
  thread_id bigint not null,
  owner_id text not null,
  role text not null,
  text text not null,
  provider text not null default '',
  suggestions text not null default '[]',
  cta_label text not null default '',
  cta_route text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists import_jobs (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  source text not null,
  filename text not null default '',
  status text not null default 'completed',
  total_count integer not null default 0,
  imported_count integer not null default 0,
  skipped_count integer not null default 0,
  failed_count integer not null default 0,
  details text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists push_subscriptions (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  endpoint text not null unique,
  p256dh_key text not null default '',
  auth_key text not null default '',
  expiration_time bigint,
  user_agent text not null default '',
  device_label text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists push_dispatch_events (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  event_key text not null,
  fingerprint text not null default '',
  send_count integer not null default 0,
  last_sent_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(owner_id, event_key)
);

alter table users add column if not exists notification_preference text not null default 'relevant';
alter table users add column if not exists avatar_url text not null default '';
alter table contacts add column if not exists linked_user_id text not null default '';
alter table contacts add column if not exists linked_user_name text not null default '';
alter table contacts add column if not exists linked_user_email text not null default '';
alter table contacts add column if not exists avatar_url text not null default '';
alter table contacts add column if not exists organization text not null default '';
alter table contacts add column if not exists demand_tags text not null default '';

create index if not exists contacts_owner_created_idx on contacts(owner_id, created_at desc, id desc);
create index if not exists contacts_owner_category_idx on contacts(owner_id, category_id);
create index if not exists contacts_owner_follow_up_idx on contacts(owner_id, next_follow_up_at);
create index if not exists public_profiles_score_idx on public_profiles(score desc, people desc);
create index if not exists users_public_visible_idx on users(public_visible, created_at desc);
create index if not exists contact_phones_owner_ddd_idx on contact_phones(owner_id, ddd);
create index if not exists contact_phones_digits_idx on contact_phones(owner_id, phone_digits);
create index if not exists contact_emails_normalized_idx on contact_emails(owner_id, normalized_email);
create index if not exists tags_owner_name_idx on tags(owner_id, normalized_name);
create index if not exists contact_tags_owner_idx on contact_tags(owner_id, tag_id);
create index if not exists custom_field_values_owner_idx on custom_field_values(owner_id, field_id);
create index if not exists groups_owner_idx on groups(owner_id, created_at desc);
create index if not exists group_members_group_idx on group_members(group_id, status);
create index if not exists group_members_user_idx on group_members(user_id, email);
create index if not exists group_contacts_group_idx on group_contacts(group_id, created_at desc);
create index if not exists group_contacts_contact_idx on group_contacts(contact_id);
create index if not exists group_messages_group_idx on group_messages(group_id, created_at asc);
create index if not exists chat_threads_owner_updated_idx on chat_threads(owner_id, updated_at desc, id desc);
create index if not exists chat_messages_thread_created_idx on chat_messages(thread_id, created_at asc, id asc);
create index if not exists import_jobs_owner_created_idx on import_jobs(owner_id, created_at desc, id desc);
create index if not exists push_subscriptions_owner_updated_idx on push_subscriptions(owner_id, updated_at desc, id desc);
create index if not exists push_dispatch_events_owner_sent_idx on push_dispatch_events(owner_id, last_sent_at desc, id desc);
